### ISSUE TITLE
Coordinate system

### ISSUE THREAD

**Issue by Ohmnivore** [rsredsq/atomic-haxe-math#3]
I don't know where else to ask :(

I tried replacing my current math lib with this one, but eventually gave up when i couldn't produce the same results. Admittedly, there are lots of calculations i had to adapt from the old lib to this one, and i probably made a mistake somewhere. Still, i may as well weed out this possible cause.

When using the glm helper functions (perspective, lookAt), what is the expected coordinate system?

**Comment by zhelezkov** [comment]
@Ohmnivore could you please provide more information?
The functions are exactly from the gl-matrix library, so they shouldn't behave as something extraordinary
https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/mat4.js#L1607
https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/mat4.js#L1711

**Comment by Ohmnivore** [comment]
double checked just now, yep i must have made a mistake elsewhere...
thanks btw!

**Comment by zhelezkov** [comment]
@Ohmnivore If you have any questions, don't hesitate to write me PM in gitter chat :)
